/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/pricing/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 公開方案列表 */
        get: {
            parameters: {
                query?: {
                    billingCycle?: components["schemas"]["BillingCycle"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            plans: components["schemas"]["PlanPublic"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 註冊並建立初始組織 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SignUpRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        /** @description session cookie（httpOnly） */
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                400: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登入 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        /** @description session cookie（httpOnly） */
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["AuthRequired"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登出（會清除 session） */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description CSRF token（double-submit cookie-to-header 或同步 token） */
                    "X-CSRF-Token": components["parameters"]["CsrfHeader"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["AuthRequired"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 取得目前登入使用者與可用組織 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MeResponse"];
                    };
                };
                401: components["responses"]["AuthRequired"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出使用者所屬組織 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            organizations: components["schemas"]["OrganizationSummary"][];
                        };
                    };
                };
                401: components["responses"]["AuthRequired"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 設定目前作用中的組織（便利功能；授權仍需 server-side 驗證） */
        put: {
            parameters: {
                query?: never;
                header: {
                    /** @description CSRF token（double-submit cookie-to-header 或同步 token） */
                    "X-CSRF-Token": components["parameters"]["CsrfHeader"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        organizationId: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrganizationSummary"];
                    };
                };
                401: components["responses"]["AuthRequired"];
                403: components["responses"]["Forbidden"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/app/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** App Dashboard（訂閱摘要 + 用量摘要 + 近期帳單） */
        get: {
            parameters: {
                query?: never;
                header: {
                    /** @description 組織上下文（後端每次驗 membership + RBAC） */
                    "X-Organization-Id": components["parameters"]["OrgHeader"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DashboardResponse"];
                    };
                };
                401: components["responses"]["AuthRequired"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/app/subscription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 訂閱摘要（含 entitlements） */
        get: {
            parameters: {
                query?: never;
                header: {
                    /** @description 組織上下文（後端每次驗 membership + RBAC） */
                    "X-Organization-Id": components["parameters"]["OrgHeader"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SubscriptionSummaryResponse"];
                    };
                };
                401: components["responses"]["AuthRequired"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/app/subscription/upgrade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 立即升級（Org Admin only；產生 proration invoice） */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description 組織上下文（後端每次驗 membership + RBAC） */
                    "X-Organization-Id": components["parameters"]["OrgHeader"];
                    /** @description CSRF token（double-submit cookie-to-header 或同步 token） */
                    "X-CSRF-Token": components["parameters"]["CsrfHeader"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpgradeRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UpgradeResponse"];
                    };
                };
                401: components["responses"]["AuthRequired"];
                403: components["responses"]["Forbidden"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/app/subscription/downgrade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 安排降級（下期生效；Org Admin only） */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description 組織上下文（後端每次驗 membership + RBAC） */
                    "X-Organization-Id": components["parameters"]["OrgHeader"];
                    /** @description CSRF token（double-submit cookie-to-header 或同步 token） */
                    "X-CSRF-Token": components["parameters"]["CsrfHeader"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DowngradeRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DowngradeResponse"];
                    };
                };
                401: components["responses"]["AuthRequired"];
                403: components["responses"]["Forbidden"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/app/subscription/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 取消訂閱（Org Admin only） */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description 組織上下文（後端每次驗 membership + RBAC） */
                    "X-Organization-Id": components["parameters"]["OrgHeader"];
                    /** @description CSRF token（double-submit cookie-to-header 或同步 token） */
                    "X-CSRF-Token": components["parameters"]["CsrfHeader"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CancelResponse"];
                    };
                };
                401: components["responses"]["AuthRequired"];
                403: components["responses"]["Forbidden"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/app/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 本期用量與限制（含策略提示） */
        get: {
            parameters: {
                query?: never;
                header: {
                    /** @description 組織上下文（後端每次驗 membership + RBAC） */
                    "X-Organization-Id": components["parameters"]["OrgHeader"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UsageOverviewResponse"];
                    };
                };
                401: components["responses"]["AuthRequired"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/app/billing/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Invoice 清單 */
        get: {
            parameters: {
                query?: {
                    status?: components["schemas"]["InvoiceStatus"];
                };
                header: {
                    /** @description 組織上下文（後端每次驗 membership + RBAC） */
                    "X-Organization-Id": components["parameters"]["OrgHeader"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InvoiceListResponse"];
                    };
                };
                401: components["responses"]["AuthRequired"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/app/billing/invoices/{invoiceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Invoice 詳細 */
        get: {
            parameters: {
                query?: never;
                header: {
                    /** @description 組織上下文（後端每次驗 membership + RBAC） */
                    "X-Organization-Id": components["parameters"]["OrgHeader"];
                };
                path: {
                    invoiceId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InvoiceDetailResponse"];
                    };
                };
                401: components["responses"]["AuthRequired"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/app/billing/invoices/{invoiceId}/simulate-payment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 模擬付款結果（dev/test only；寫入 inbox 並走同一處理流程） */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description 組織上下文（後端每次驗 membership + RBAC） */
                    "X-Organization-Id": components["parameters"]["OrgHeader"];
                    /** @description CSRF token（double-submit cookie-to-header 或同步 token） */
                    "X-CSRF-Token": components["parameters"]["CsrfHeader"];
                };
                path: {
                    invoiceId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        result: "success" | "fail";
                    };
                };
            };
            responses: {
                /** @description Accepted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["AuthRequired"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/app/billing/payment-methods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 付款方式列表（Org Admin only） */
        get: {
            parameters: {
                query?: never;
                header: {
                    /** @description 組織上下文（後端每次驗 membership + RBAC） */
                    "X-Organization-Id": components["parameters"]["OrgHeader"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaymentMethodsResponse"];
                    };
                };
                401: components["responses"]["AuthRequired"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        /** 新增/更新付款方式（Org Admin only） */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description 組織上下文（後端每次驗 membership + RBAC） */
                    "X-Organization-Id": components["parameters"]["OrgHeader"];
                    /** @description CSRF token（double-submit cookie-to-header 或同步 token） */
                    "X-CSRF-Token": components["parameters"]["CsrfHeader"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpsertPaymentMethodRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaymentMethodsResponse"];
                    };
                };
                401: components["responses"]["AuthRequired"];
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/app/org/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 組織成員列表（Org Admin only） */
        get: {
            parameters: {
                query?: never;
                header: {
                    /** @description 組織上下文（後端每次驗 membership + RBAC） */
                    "X-Organization-Id": components["parameters"]["OrgHeader"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MembersResponse"];
                    };
                };
                401: components["responses"]["AuthRequired"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        /** 邀請成員（Org Admin only） */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description 組織上下文（後端每次驗 membership + RBAC） */
                    "X-Organization-Id": components["parameters"]["OrgHeader"];
                    /** @description CSRF token（double-submit cookie-to-header 或同步 token） */
                    "X-CSRF-Token": components["parameters"]["CsrfHeader"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["InviteMemberRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Member"];
                    };
                };
                401: components["responses"]["AuthRequired"];
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/app/org/members/{memberId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 移除成員（soft delete；Org Admin only） */
        delete: {
            parameters: {
                query?: never;
                header: {
                    /** @description 組織上下文（後端每次驗 membership + RBAC） */
                    "X-Organization-Id": components["parameters"]["OrgHeader"];
                    /** @description CSRF token（double-submit cookie-to-header 或同步 token） */
                    "X-CSRF-Token": components["parameters"]["CsrfHeader"];
                };
                path: {
                    memberId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["AuthRequired"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        /** 調整成員角色（Org Admin only） */
        patch: {
            parameters: {
                query?: never;
                header: {
                    /** @description 組織上下文（後端每次驗 membership + RBAC） */
                    "X-Organization-Id": components["parameters"]["OrgHeader"];
                    /** @description CSRF token（double-submit cookie-to-header 或同步 token） */
                    "X-CSRF-Token": components["parameters"]["CsrfHeader"];
                };
                path: {
                    memberId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        role: components["schemas"]["OrganizationRole"];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Member"];
                    };
                };
                401: components["responses"]["AuthRequired"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/admin/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 方案列表（Platform Admin） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            plans: components["schemas"]["PlanAdmin"][];
                        };
                    };
                };
                401: components["responses"]["AuthRequired"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        /** 建立方案（Platform Admin） */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description CSRF token（double-submit cookie-to-header 或同步 token） */
                    "X-CSRF-Token": components["parameters"]["CsrfHeader"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PlanUpsertRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlanAdmin"];
                    };
                };
                400: components["responses"]["ValidationError"];
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/plans/{planId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 更新方案（Platform Admin） */
        put: {
            parameters: {
                query?: never;
                header: {
                    /** @description CSRF token（double-submit cookie-to-header 或同步 token） */
                    "X-CSRF-Token": components["parameters"]["CsrfHeader"];
                };
                path: {
                    planId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PlanUpsertRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlanAdmin"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["AuthRequired"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Dashboard（Platform Admin） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminDashboardResponse"];
                    };
                };
                401: components["responses"]["AuthRequired"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/overrides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 強制停權/解除（Platform Admin） */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description CSRF token（double-submit cookie-to-header 或同步 token） */
                    "X-CSRF-Token": components["parameters"]["CsrfHeader"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminForceStatusRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminForceStatusResponse"];
                    };
                };
                401: components["responses"]["AuthRequired"];
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 稽核查詢（Platform Admin） */
        get: {
            parameters: {
                query?: {
                    actorUserId?: string;
                    organizationId?: string;
                    action?: string;
                    limit?: number;
                    cursor?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuditLogsResponse"];
                    };
                };
                401: components["responses"]["AuthRequired"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/payment/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 付款供應商回調（去重寫入 inbox 後回 2xx） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    provider: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            responses: {
                /** @description Accepted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        BillingCycle: "monthly" | "yearly";
        /** @enum {string} */
        OrganizationRole: "END_USER" | "ORG_ADMIN";
        /** @enum {string} */
        SubscriptionStatus: "Trial" | "Active" | "PastDue" | "Suspended" | "Canceled" | "Expired";
        /** @enum {string} */
        InvoiceStatus: "Draft" | "Open" | "Paid" | "Failed" | "Voided";
        ErrorResponse: {
            /** @example FORBIDDEN */
            errorCode: string;
            /** @example Access denied */
            message: string;
            requestId?: string | null;
        };
        AdminDashboardResponse: {
            orgCount: number;
            userCount: number;
            activeSubscriptions: number;
            pastDueSubscriptions: number;
            suspendedSubscriptions: number;
            expiredSubscriptions: number;
            openInvoices: number;
            revenueTotalCents: number;
        };
        PlanPublic: {
            id: string;
            name: string;
            billingCycle: components["schemas"]["BillingCycle"];
            priceCents: number;
            currency: string;
            isActive: boolean;
            limits: {
                [key: string]: unknown;
            };
            features: {
                [key: string]: boolean;
            };
        };
        PlanAdmin: components["schemas"]["PlanPublic"] & {
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        PlanUpsertRequest: {
            name: string;
            billingCycle: components["schemas"]["BillingCycle"];
            priceCents: number;
            currency: string;
            isActive: boolean;
            limits: {
                [key: string]: unknown;
            };
            features: {
                [key: string]: boolean;
            };
        };
        SignUpRequest: {
            /** Format: email */
            email: string;
            password: string;
            organizationName: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        User: {
            id: string;
            /** Format: email */
            email: string;
            isPlatformAdmin: boolean;
        };
        OrganizationSummary: {
            id: string;
            name: string;
            /** @enum {string} */
            memberRole: "END_USER" | "ORG_ADMIN";
        };
        AuthResponse: {
            user: components["schemas"]["User"];
            organizations: components["schemas"]["OrganizationSummary"][];
            currentOrganization: components["schemas"]["OrganizationSummary"];
        };
        MeResponse: components["schemas"]["AuthResponse"];
        Period: {
            /** Format: date-time */
            start: string;
            /** Format: date-time */
            end: string;
        };
        PendingChange: {
            pendingPlanId: string;
            /** Format: date-time */
            effectiveAt: string;
        };
        Entitlements: {
            features: {
                [key: string]: boolean;
            };
            limits: {
                [key: string]: Record<string, never>;
            };
            statusReason?: string;
        };
        SubscriptionSummaryResponse: {
            status: components["schemas"]["SubscriptionStatus"];
            billingCycle: components["schemas"]["BillingCycle"];
            plan: components["schemas"]["PlanPublic"];
            currentPeriod: components["schemas"]["Period"];
            /** Format: date-time */
            trialEndAt?: string | null;
            /** Format: date-time */
            gracePeriodEndAt?: string | null;
            pendingChange?: components["schemas"]["PendingChange"];
            entitlements: components["schemas"]["Entitlements"];
        };
        UpgradeRequest: {
            targetPlanId: string;
            targetBillingCycle: components["schemas"]["BillingCycle"];
            confirm: boolean;
        };
        Invoice: {
            id: string;
            status: components["schemas"]["InvoiceStatus"];
            billingPeriod: components["schemas"]["Period"];
            totalCents: number;
            currency: string;
            /** Format: date-time */
            dueAt?: string | null;
            /** Format: date-time */
            paidAt?: string | null;
            /** Format: date-time */
            failedAt?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        UpgradeResponse: {
            subscription: components["schemas"]["SubscriptionSummaryResponse"];
            prorationInvoice: components["schemas"]["Invoice"];
        };
        DowngradeRequest: {
            targetPlanId: string;
            targetBillingCycle: components["schemas"]["BillingCycle"];
            confirm: boolean;
        };
        DowngradeResponse: {
            subscription: components["schemas"]["SubscriptionSummaryResponse"];
        };
        CancelResponse: {
            subscription: components["schemas"]["SubscriptionSummaryResponse"];
        };
        /** @enum {string} */
        MeterPolicy: "block" | "throttle" | "overage";
        /** @enum {string} */
        MeterStatus: "ok" | "nearLimit" | "overLimit";
        UsageMeterItem: {
            /** @enum {string} */
            code: "API_CALLS" | "STORAGE_BYTES" | "USER_COUNT" | "PROJECT_COUNT";
            name: string;
            unit: string;
            value: number;
            limit?: number | null;
            policy: components["schemas"]["MeterPolicy"];
            status: components["schemas"]["MeterStatus"];
            /** Format: date-time */
            resetAt: string;
        };
        UsageOverviewResponse: {
            meters: components["schemas"]["UsageMeterItem"][];
        };
        InvoiceListResponse: {
            invoices: components["schemas"]["Invoice"][];
        };
        InvoiceLineItem: {
            /** @enum {string} */
            type: "RECURRING" | "PRORATION" | "OVERAGE" | "TAX";
            description: string;
            amountCents: number;
            quantity?: number | null;
            meterCode?: string | null;
        };
        InvoiceDetailResponse: {
            invoice: components["schemas"]["Invoice"];
            lineItems: components["schemas"]["InvoiceLineItem"][];
        };
        PaymentMethod: {
            id: string;
            provider: string;
            isDefault: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        PaymentMethodsResponse: {
            paymentMethods: components["schemas"]["PaymentMethod"][];
        };
        UpsertPaymentMethodRequest: {
            paymentMethodToken: string;
            setDefault?: boolean;
        };
        Member: {
            id: string;
            /** Format: email */
            email: string;
            /** @enum {string} */
            role: "END_USER" | "ORG_ADMIN";
            /** @enum {string} */
            status: "ACTIVE" | "REMOVED";
        };
        MembersResponse: {
            members: components["schemas"]["Member"][];
        };
        InviteMemberRequest: {
            /** Format: email */
            email: string;
            /** @enum {string} */
            role: "END_USER" | "ORG_ADMIN";
        };
        AdminForceStatusRequest: {
            organizationId: string;
            /** @enum {string} */
            forcedStatus: "NONE" | "Suspended" | "Expired";
            reason: string;
        };
        AdminForceStatusResponse: {
            /** @enum {string} */
            forcedStatus: "NONE" | "Suspended" | "Expired";
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            revokedAt?: string | null;
        };
        AuditLog: {
            id: string;
            actorUserId: string;
            /** @enum {string} */
            roleContext: "GUEST" | "END_USER" | "ORG_ADMIN" | "PLATFORM_ADMIN" | "SYSTEM";
            organizationId?: string | null;
            action: string;
            targetType: string;
            targetId?: string | null;
            payload: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            createdAt: string;
        };
        AuditLogsResponse: {
            auditLogs: components["schemas"]["AuditLog"][];
            nextCursor?: string | null;
        };
        DashboardResponse: {
            subscription: components["schemas"]["SubscriptionSummaryResponse"];
            usage: components["schemas"]["UsageOverviewResponse"];
            recentInvoices: components["schemas"]["Invoice"][];
        };
    };
    responses: {
        /** @description 未登入 */
        AuthRequired: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 無權限 */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 找不到資源 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 狀態衝突/不可逆規則阻擋 */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 輸入驗證錯誤 */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"] & {
                    details?: {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    parameters: {
        /** @description 組織上下文（後端每次驗 membership + RBAC） */
        OrgHeader: string;
        /** @description CSRF token（double-submit cookie-to-header 或同步 token） */
        CsrfHeader: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
