// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/audit" | "/admin/boards" | "/admin/moderators" | "/admin/reports" | "/admin/users" | "/boards/[boardId]" | "/login" | "/mod" | "/mod/boards/[boardId]/reports" | "/register" | "/search" | "/threads/[threadId]"
type AppRouteHandlerRoutes = "/api/admin/audit" | "/api/admin/boards" | "/api/admin/boards/[boardId]" | "/api/admin/moderators" | "/api/admin/reports" | "/api/admin/users" | "/api/admin/users/[userId]/ban" | "/api/admin/users/[userId]/unban" | "/api/auth/login" | "/api/auth/logout" | "/api/auth/register" | "/api/boards" | "/api/boards/[boardId]/threads" | "/api/csrf" | "/api/favorites" | "/api/likes" | "/api/mod/boards/[boardId]/reports" | "/api/mod/posts/[postId]/hide" | "/api/mod/posts/[postId]/unhide" | "/api/mod/threads/[threadId]/hide" | "/api/mod/threads/[threadId]/lock" | "/api/mod/threads/[threadId]/unhide" | "/api/mod/threads/[threadId]/unlock" | "/api/posts/[postId]" | "/api/reports" | "/api/reports/[reportId]/resolve" | "/api/search" | "/api/session/me" | "/api/threads" | "/api/threads/[threadId]" | "/api/threads/[threadId]/posts" | "/api/threads/[threadId]/publish"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = "/api/[[...path]]"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/audit": {}
  "/admin/boards": {}
  "/admin/moderators": {}
  "/admin/reports": {}
  "/admin/users": {}
  "/api/[[...path]]": { "path"?: string[]; }
  "/api/admin/audit": {}
  "/api/admin/boards": {}
  "/api/admin/boards/[boardId]": { "boardId": string; }
  "/api/admin/moderators": {}
  "/api/admin/reports": {}
  "/api/admin/users": {}
  "/api/admin/users/[userId]/ban": { "userId": string; }
  "/api/admin/users/[userId]/unban": { "userId": string; }
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/register": {}
  "/api/boards": {}
  "/api/boards/[boardId]/threads": { "boardId": string; }
  "/api/csrf": {}
  "/api/favorites": {}
  "/api/likes": {}
  "/api/mod/boards/[boardId]/reports": { "boardId": string; }
  "/api/mod/posts/[postId]/hide": { "postId": string; }
  "/api/mod/posts/[postId]/unhide": { "postId": string; }
  "/api/mod/threads/[threadId]/hide": { "threadId": string; }
  "/api/mod/threads/[threadId]/lock": { "threadId": string; }
  "/api/mod/threads/[threadId]/unhide": { "threadId": string; }
  "/api/mod/threads/[threadId]/unlock": { "threadId": string; }
  "/api/posts/[postId]": { "postId": string; }
  "/api/reports": {}
  "/api/reports/[reportId]/resolve": { "reportId": string; }
  "/api/search": {}
  "/api/session/me": {}
  "/api/threads": {}
  "/api/threads/[threadId]": { "threadId": string; }
  "/api/threads/[threadId]/posts": { "threadId": string; }
  "/api/threads/[threadId]/publish": { "threadId": string; }
  "/boards/[boardId]": { "boardId": string; }
  "/login": {}
  "/mod": {}
  "/mod/boards/[boardId]/reports": { "boardId": string; }
  "/register": {}
  "/search": {}
  "/threads/[threadId]": { "threadId": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
