// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(auth)/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../../app/(auth)/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(forum)/admin/audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/audit">> = Specific
  const handler = {} as typeof import("../../../app/(forum)/admin/audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(forum)/admin/boards/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/boards">> = Specific
  const handler = {} as typeof import("../../../app/(forum)/admin/boards/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(forum)/admin/moderators/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/moderators">> = Specific
  const handler = {} as typeof import("../../../app/(forum)/admin/moderators/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(forum)/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../app/(forum)/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(forum)/admin/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/reports">> = Specific
  const handler = {} as typeof import("../../../app/(forum)/admin/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(forum)/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../../app/(forum)/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(forum)/boards/[boardId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/boards/[boardId]">> = Specific
  const handler = {} as typeof import("../../../app/(forum)/boards/[boardId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(forum)/mod/boards/[boardId]/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mod/boards/[boardId]/reports">> = Specific
  const handler = {} as typeof import("../../../app/(forum)/mod/boards/[boardId]/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(forum)/mod/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mod">> = Specific
  const handler = {} as typeof import("../../../app/(forum)/mod/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(forum)/search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/search">> = Specific
  const handler = {} as typeof import("../../../app/(forum)/search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(forum)/threads/[threadId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/threads/[threadId]">> = Specific
  const handler = {} as typeof import("../../../app/(forum)/threads/[threadId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(public)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/(public)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/audit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/audit">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/audit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/boards/[boardId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/boards/[boardId]">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/boards/[boardId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/boards/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/boards">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/boards/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/moderators/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/moderators">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/moderators/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/reports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reports">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/reports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/users/[userId]/ban/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users/[userId]/ban">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/users/[userId]/ban/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/users/[userId]/unban/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users/[userId]/unban">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/users/[userId]/unban/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/boards/[boardId]/threads/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/boards/[boardId]/threads">> = Specific
  const handler = {} as typeof import("../../../app/api/boards/[boardId]/threads/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/boards/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/boards">> = Specific
  const handler = {} as typeof import("../../../app/api/boards/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/csrf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/csrf">> = Specific
  const handler = {} as typeof import("../../../app/api/csrf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/favorites/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/favorites">> = Specific
  const handler = {} as typeof import("../../../app/api/favorites/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/likes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/likes">> = Specific
  const handler = {} as typeof import("../../../app/api/likes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mod/boards/[boardId]/reports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mod/boards/[boardId]/reports">> = Specific
  const handler = {} as typeof import("../../../app/api/mod/boards/[boardId]/reports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mod/posts/[postId]/hide/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mod/posts/[postId]/hide">> = Specific
  const handler = {} as typeof import("../../../app/api/mod/posts/[postId]/hide/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mod/posts/[postId]/unhide/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mod/posts/[postId]/unhide">> = Specific
  const handler = {} as typeof import("../../../app/api/mod/posts/[postId]/unhide/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mod/threads/[threadId]/hide/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mod/threads/[threadId]/hide">> = Specific
  const handler = {} as typeof import("../../../app/api/mod/threads/[threadId]/hide/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mod/threads/[threadId]/lock/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mod/threads/[threadId]/lock">> = Specific
  const handler = {} as typeof import("../../../app/api/mod/threads/[threadId]/lock/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mod/threads/[threadId]/unhide/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mod/threads/[threadId]/unhide">> = Specific
  const handler = {} as typeof import("../../../app/api/mod/threads/[threadId]/unhide/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mod/threads/[threadId]/unlock/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mod/threads/[threadId]/unlock">> = Specific
  const handler = {} as typeof import("../../../app/api/mod/threads/[threadId]/unlock/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/posts/[postId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/posts/[postId]">> = Specific
  const handler = {} as typeof import("../../../app/api/posts/[postId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/reports/[reportId]/resolve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/[reportId]/resolve">> = Specific
  const handler = {} as typeof import("../../../app/api/reports/[reportId]/resolve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/reports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports">> = Specific
  const handler = {} as typeof import("../../../app/api/reports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/search">> = Specific
  const handler = {} as typeof import("../../../app/api/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/session/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/session/me">> = Specific
  const handler = {} as typeof import("../../../app/api/session/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/threads/[threadId]/posts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/threads/[threadId]/posts">> = Specific
  const handler = {} as typeof import("../../../app/api/threads/[threadId]/posts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/threads/[threadId]/publish/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/threads/[threadId]/publish">> = Specific
  const handler = {} as typeof import("../../../app/api/threads/[threadId]/publish/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/threads/[threadId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/threads/[threadId]">> = Specific
  const handler = {} as typeof import("../../../app/api/threads/[threadId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/threads/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/threads">> = Specific
  const handler = {} as typeof import("../../../app/api/threads/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
