export const ErrorCodes = {
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',

  AUTH_EMAIL_EXISTS: 'AUTH_EMAIL_EXISTS',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_USER_SUSPENDED: 'AUTH_USER_SUSPENDED',

  PASSWORD_RESET_INVALID: 'PASSWORD_RESET_INVALID',

  BOOKING_SEAT_FULL: 'BOOKING_SEAT_FULL',
  BOOKING_DUPLICATE: 'BOOKING_DUPLICATE',
  BOOKING_NOT_CANCELLABLE: 'BOOKING_NOT_CANCELLABLE',
  BOOKING_ALREADY_CANCELLED: 'BOOKING_ALREADY_CANCELLED',
  BOOKING_STATE_INVALID_TRANSITION: 'BOOKING_STATE_INVALID_TRANSITION',

  TIMESLOT_OVERLAP: 'TIMESLOT_OVERLAP',
  TIMESLOT_CAPACITY_BELOW_BOOKED: 'TIMESLOT_CAPACITY_BELOW_BOOKED',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
