export const AUDIT_ACTIONS = {
  AUTH_SIGNUP: 'AUTH_SIGNUP',
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_LOGOUT: 'AUTH_LOGOUT',

  ORG_SET_ACTIVE: 'ORG_SET_ACTIVE',

  SUBSCRIPTION_UPGRADE: 'SUBSCRIPTION_UPGRADE',
  SUBSCRIPTION_DOWNGRADE: 'SUBSCRIPTION_DOWNGRADE',
  SUBSCRIPTION_CANCEL: 'SUBSCRIPTION_CANCEL',
  SUBSCRIPTION_STATUS_CHANGE: 'SUBSCRIPTION_STATUS_CHANGE',

  INVOICE_CREATED: 'INVOICE_CREATED',
  INVOICE_STATUS_CHANGE: 'INVOICE_STATUS_CHANGE',

  MEMBER_INVITE: 'MEMBER_INVITE',
  MEMBER_ROLE_CHANGE: 'MEMBER_ROLE_CHANGE',
  MEMBER_REMOVED: 'MEMBER_REMOVED',

  ADMIN_OVERRIDE_CREATED: 'ADMIN_OVERRIDE_CREATED',
  ADMIN_OVERRIDE_REVOKED: 'ADMIN_OVERRIDE_REVOKED',
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];

export const AUDIT_REQUIRED_ACTION_PREFIXES: ReadonlyArray<string> = [
  'SUBSCRIPTION_',
  'INVOICE_',
  'ADMIN_OVERRIDE_',
  'MEMBER_',
];
