-- Immutability enforcement (SQLite)
-- Prevent UPDATE/DELETE on immutable tables.

CREATE TRIGGER IF NOT EXISTS "SurveyPublish_prevent_update"
BEFORE UPDATE ON "SurveyPublish"
BEGIN
	SELECT RAISE(ABORT, 'IMMUTABLE_SURVEY_PUBLISH');
END;

CREATE TRIGGER IF NOT EXISTS "SurveyPublish_prevent_delete"
BEFORE DELETE ON "SurveyPublish"
BEGIN
	SELECT RAISE(ABORT, 'IMMUTABLE_SURVEY_PUBLISH');
END;

CREATE TRIGGER IF NOT EXISTS "Response_prevent_update"
BEFORE UPDATE ON "Response"
BEGIN
	SELECT RAISE(ABORT, 'IMMUTABLE_RESPONSE');
END;

CREATE TRIGGER IF NOT EXISTS "Response_prevent_delete"
BEFORE DELETE ON "Response"
BEGIN
	SELECT RAISE(ABORT, 'IMMUTABLE_RESPONSE');
END;

CREATE TRIGGER IF NOT EXISTS "Answer_prevent_update"
BEFORE UPDATE ON "Answer"
BEGIN
	SELECT RAISE(ABORT, 'IMMUTABLE_ANSWER');
END;

CREATE TRIGGER IF NOT EXISTS "Answer_prevent_delete"
BEFORE DELETE ON "Answer"
BEGIN
	SELECT RAISE(ABORT, 'IMMUTABLE_ANSWER');
END;