export const ERROR_CODES = {
  INVALID_TRANSITION: 'INVALID_TRANSITION',
  NOT_VISIBLE: 'NOT_VISIBLE',
  ALREADY_TAKEN: 'ALREADY_TAKEN',
  CLOSED_FINAL: 'CLOSED_FINAL',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]
