export const AuditActions = {
  AUTH_SIGNUP: 'AUTH_SIGNUP',
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_LOGOUT: 'AUTH_LOGOUT',

  CATALOG_PRODUCT_CREATE: 'CATALOG_PRODUCT_CREATE',
  CATALOG_PRODUCT_UPDATE: 'CATALOG_PRODUCT_UPDATE',
  CATALOG_PRODUCT_STATUS_CHANGE: 'CATALOG_PRODUCT_STATUS_CHANGE',

  CART_ITEM_ADD: 'CART_ITEM_ADD',
  CART_ITEM_UPDATE: 'CART_ITEM_UPDATE',
  CART_ITEM_REMOVE: 'CART_ITEM_REMOVE',

  CHECKOUT_CREATE: 'CHECKOUT_CREATE',
  PAYMENT_CALLBACK: 'PAYMENT_CALLBACK',
  ORDER_CANCEL: 'ORDER_CANCEL',

  REFUND_REQUEST_CREATE: 'REFUND_REQUEST_CREATE',
  REVIEW_CREATE: 'REVIEW_CREATE',

  SELLER_APPLICATION_SUBMIT: 'SELLER_APPLICATION_SUBMIT',
  SELLER_APPLICATION_DECIDE: 'SELLER_APPLICATION_DECIDE',
} as const;

export type AuditAction = (typeof AuditActions)[keyof typeof AuditActions];
