export const ERROR_CODES = {
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',
  CONFLICT: 'CONFLICT',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  CSRF_TOKEN_INVALID: 'CSRF_TOKEN_INVALID',
  ORG_MEMBERSHIP_REQUIRED: 'ORG_MEMBERSHIP_REQUIRED',
  PROJECT_MEMBERSHIP_REQUIRED: 'PROJECT_MEMBERSHIP_REQUIRED',
  ROLE_REQUIRED: 'ROLE_REQUIRED',
  ORG_SUSPENDED: 'ORG_SUSPENDED',
  PROJECT_ARCHIVED: 'PROJECT_ARCHIVED',
  ISSUE_STATUS_DEPRECATED: 'ISSUE_STATUS_DEPRECATED',
  ISSUE_TRANSITION_INVALID: 'ISSUE_TRANSITION_INVALID',
  WORKFLOW_INVALID: 'WORKFLOW_INVALID',
  SPRINT_INVALID: 'SPRINT_INVALID',
  EPIC_LINK_INVALID: 'EPIC_LINK_INVALID',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export interface ErrorResponseBody {
  statusCode: number;
  errorCode: ErrorCode;
  message: string;
  timestamp: string;
  path: string;
  requestId: string;
}
