export const AuditActions = {
  PLATFORM_ORG_CREATED: 'PLATFORM_ORG_CREATED',
  PLATFORM_ORG_UPDATED: 'PLATFORM_ORG_UPDATED',
  ORG_SUSPENDED: 'ORG_SUSPENDED',
  ORG_UNSUSPENDED: 'ORG_UNSUSPENDED',
  PROJECT_CREATED: 'PROJECT_CREATED',
  PROJECT_ARCHIVED: 'PROJECT_ARCHIVED',
  ORG_MEMBER_ROLE_UPDATED: 'ORG_MEMBER_ROLE_UPDATED',
  ORG_MEMBER_REMOVED: 'ORG_MEMBER_REMOVED',
  PROJECT_MEMBER_ROLE_UPDATED: 'PROJECT_MEMBER_ROLE_UPDATED',
  PROJECT_MEMBER_REMOVED: 'PROJECT_MEMBER_REMOVED',
  ORG_INVITE_CREATED: 'ORG_INVITE_CREATED',
  ORG_INVITE_ACCEPTED: 'ORG_INVITE_ACCEPTED',
  ISSUE_CREATED: 'ISSUE_CREATED',
  ISSUE_UPDATED: 'ISSUE_UPDATED',
  ISSUE_TRANSITIONED: 'ISSUE_TRANSITIONED',
  ISSUE_COMMENT_CREATED: 'ISSUE_COMMENT_CREATED',
  SPRINT_CREATED: 'SPRINT_CREATED',
  SPRINT_STARTED: 'SPRINT_STARTED',
  SPRINT_CLOSED: 'SPRINT_CLOSED',
} as const;

export type AuditAction = (typeof AuditActions)[keyof typeof AuditActions];
