export const ErrorCodes = {
  // Generic
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  // Auth
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  USER_SUSPENDED: 'USER_SUSPENDED',

  // Booking domain
  CAPACITY_FULL: 'CAPACITY_FULL',
  DUPLICATE_BOOKING: 'DUPLICATE_BOOKING',
  DEADLINE_PASSED: 'DEADLINE_PASSED',
  INVALID_TRANSITION: 'INVALID_TRANSITION',
  ALREADY_CANCELLED: 'ALREADY_CANCELLED',
  NOT_ACCESSIBLE: 'NOT_ACCESSIBLE',

  // Password reset
  RESET_TOKEN_INVALID: 'RESET_TOKEN_INVALID',
  RESET_TOKEN_EXPIRED: 'RESET_TOKEN_EXPIRED',
  RESET_TOKEN_USED: 'RESET_TOKEN_USED',
} as const

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes]
