export const ErrorCodes = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  ORG_SUSPENDED: 'ORG_SUSPENDED',
  PROJECT_ARCHIVED: 'PROJECT_ARCHIVED',
  ISSUE_STATUS_DEPRECATED: 'ISSUE_STATUS_DEPRECATED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
